export default [
  {
    id: 1,
    businessName: 'EcoGreen Disposal',
    delegatedPerson: 'Adam Nelson',
    flagged: false,
    description:
      '<p>The driver <b>failed to collect all waste bins</b> from the site, including those marked as <i>priority hazardous materials</i>. This delay has resulted in health risks and disruptions to operations.</p><p>Additionally, <b>previously cleaned areas</b> were left dirty due to improper handling of the waste, adding extra work for our team. <u>We require immediate resolution to ensure compliance with safety standards.</u></p>',
    raisedBy: 'Sophia Clark',
    timestamp: '2024-11-11T10:00:00Z',
    relativeTime: '7 days ago',
    advisedRootCause: 'Driver Oversight',
    advisedCorrectiveAction: 'Route and Checklist Review',
    departmentResponsible: 'Fleet Management',
    images: [
      {
        title: 'Uncollected Hazardous Bin',
        size: '5.12MB',
        source: 'https://picsum.photos/1280/720?random=11',
      },
      {
        title: 'Waste Left Behind',
        size: '3.21MB',
        source: 'https://picsum.photos/1280/720?random=10',
      },
    ],
    attachments: [
      {
        filename: 'incident_report.pdf',
        size: '2.4MB',
        url: 'https://example.com/attachments/incident_report_1.pdf',
      },
      {
        filename: 'compliance_checklist.xlsx',
        size: '1.2MB',
        url: 'https://example.com/attachments/compliance_checklist_1.xlsx',
      },
    ],
    type: 'Issue',
    open: false,
    unseenUpdates: 2,
    updates: [
      {
        timestamp: '2024-11-11T10:00:00Z',
        relativeTime: '7 days ago',
        loggedBy: 'System',
        update: 'Issue opened and assigned to Fleet Management.',
        resolved: false,
      },
      {
        timestamp: '2024-11-11T15:30:00Z',
        relativeTime: '7 days ago',
        loggedBy: 'Adam Nelson',
        update: 'Fleet contacted. Follow-up scheduled for next morning to complete collection.',
        resolved: false,
        images: [
          {
            title: 'Overflowing Waste',
            size: '4.55MB',
            source: 'https://picsum.photos/1280/720?random=3',
          },
        ],
      },
      {
        timestamp: '2024-11-12T09:00:00Z',
        relativeTime: '6 days ago',
        loggedBy: 'System',
        update: 'Collection completed. Awaiting customer confirmation.',
        resolved: false,
      },
      {
        timestamp: '2024-11-12T14:15:00Z',
        relativeTime: '6 days ago',
        loggedBy: 'Sarah Thompson',
        update: 'Customer confirmed completion. New collection schedule implemented.',
        resolved: true,
        proposedResolution: {
          rootCause: 'Driver Error',
          rootCauseDetails:
            'Driver failed to follow established collection protocols and missed critical hazardous waste bins. Investigation revealed inadequate route documentation and checklist usage.',
          correctiveAction: 'Route and Checklist Review',
          correctiveActionDetails:
            'Implemented new digital checklist system with mandatory completion requirements. Updated route documentation with clear hazardous waste priorities.',
          status: 'accepted',
        },
      },
    ],
  },
  {
    id: 2,
    businessName: 'ClearWaste Inc.',
    delegatedPerson: 'Emma Wilson',
    flagged: true,
    description:
      '<p>The <strong>scheduled waste collection</strong> was missed twice this week, with no prior notice or communication from your team. This has led to <i>overflowing waste containers</i> and significant hygiene issues across our site.</p><p>We urgently need better communication about rescheduling and expect a detailed explanation for these repeated failures.</p>',
    raisedBy: 'Lucas Johnson',
    timestamp: '2024-11-09T12:00:00Z',
    relativeTime: '9 days ago',
    advisedRootCause: 'Scheduling Conflict',
    advisedCorrectiveAction: 'Enhanced Notification System',
    departmentResponsible: 'Customer Service',
    images: [
      {
        title: 'Overflowing Waste',
        size: '4.55MB',
        source: 'https://picsum.photos/1280/720?random=1',
      },
      {
        title: 'Overflowed Containers',
        size: '3.75MB',
        source: 'https://picsum.photos/1280/720?random=2',
      },
    ],
    attachments: [
      {
        filename: 'missed_pickup_schedule.pdf',
        size: '1.8MB',
        url: 'https://example.com/attachments/missed_pickup_schedule_2.pdf',
      },
      {
        filename: 'communication_log.docx',
        size: '0.85MB',
        url: 'https://example.com/attachments/communication_log_2.docx',
      },
      {
        filename: 'customer_feedback.txt',
        size: '0.12MB',
        url: 'https://example.com/attachments/customer_feedback_2.txt',
      },
    ],
    type: 'Issue',
    open: false,
    unseenUpdates: 3,
    updates: [
      {
        timestamp: '2024-11-09T12:00:00Z',
        relativeTime: '9 days ago',
        loggedBy: 'System',
        update: 'Issue reported to Customer Service.',
        resolved: false,
      },
      {
        timestamp: '2024-11-10T08:15:00Z',
        relativeTime: '8 days ago',
        loggedBy: 'Emma Wilson',
        update: 'Customer informed of rescheduled pickup for the next day.',
        resolved: false,
      },
      {
        timestamp: '2024-11-11T07:00:00Z',
        relativeTime: '7 days ago',
        loggedBy: 'System',
        update: 'Pickup completed. Customer informed of resolution.',
        resolved: false,
      },
      {
        timestamp: '2024-11-11T13:45:00Z',
        relativeTime: '7 days ago',
        loggedBy: 'Emma Wilson',
        update: 'Follow-up communication sent to prevent future occurrences.',
        resolved: false,
      },
      {
        timestamp: '2024-11-12T09:30:00Z',
        relativeTime: '6 days ago',
        loggedBy: 'System',
        update: 'Case closed after customer acknowledgment.',
        resolved: true,
        proposedResolution: {
          rootCause: 'Scheduling Conflict',
          rootCauseDetails:
            'Multiple scheduling conflicts arose from uncoordinated route changes and inadequate communication between dispatch and drivers.',
          correctiveAction: 'Update Communication Protocols',
          correctiveActionDetails:
            'Implemented real-time route update notifications and mandatory acknowledgment system for all schedule changes.',
          status: 'accepted',
        },
      },
    ],
  },
  {
    id: 3,
    businessName: 'GreenWaste Services',
    delegatedPerson: 'Michael Torres',
    flagged: true,
    description:
      '<p>The waste collection vehicle <b>damaged the loading dock</b> during pickup, leading to a significant repair cost. This issue has also disrupted our operations as trucks can no longer access the dock safely.</p><p><strong>Urgent action</strong> is required to prevent further complications and address this matter with your drivers.</p>',
    raisedBy: 'Isabella Garcia',
    timestamp: '2024-11-10T16:30:00Z',
    relativeTime: '8 days ago',
    advisedRootCause: 'Driver Error',
    advisedCorrectiveAction: 'Driver Safety Training',
    departmentResponsible: 'Safety',
    images: [
      {
        title: 'Damaged Loading Dock',
        size: '5.6MB',
        source: 'https://picsum.photos/1280/720?random=4',
      },
    ],
    attachments: [
      {
        filename: 'damage_assessment.pdf',
        size: '3.2MB',
        url: 'https://example.com/attachments/damage_assessment_3.pdf',
      },
    ],
    type: 'Disaster',
    open: true,
    unseenUpdates: 1,
    updates: [
      {
        timestamp: '2024-11-10T16:30:00Z',
        relativeTime: '8 days ago',
        loggedBy: 'System',
        update: 'Disaster reported to Safety Department.',
        resolved: false,
      },
      {
        timestamp: '2024-11-11T09:30:00Z',
        relativeTime: '7 days ago',
        loggedBy: 'Michael Torres',
        update: 'Proposed resolution plan submitted for review.',
        resolved: false,
        proposedResolution: {
          rootCause: 'Driver Error',
          rootCauseDetails:
            'Investigation revealed gaps in driver safety training and dock approach procedures.',
          correctiveAction: 'Enhanced Driver Training',
          correctiveActionDetails:
            'Pending implementation of comprehensive dock safety training program and installation of guide markers.',
          status: 'pending',
        },
      },
    ],
  },
  {
    id: 4,
    businessName: 'MetroWaste Solutions',
    delegatedPerson: 'Ethan Hayes',
    flagged: true,
    description:
      '<p>Our <b>scheduling system experienced a critical failure</b> during peak hours, resulting in multiple missed collections across the metropolitan area. The system outage lasted approximately 4 hours, impacting over 50 scheduled pickups.</p><p>Emergency manual dispatch was implemented but <i>several high-priority clients were affected</i>.</p>',
    raisedBy: 'Noah Cooper',
    timestamp: '2024-11-14T08:30:00Z',
    relativeTime: '4 days ago',
    advisedRootCause: 'Equipment Failure',
    advisedCorrectiveAction: 'Equipment Maintenance',
    departmentResponsible: 'IT Support',
    type: 'Disaster',
    open: false,
    unseenUpdates: 2,
    images: [
      {
        title: 'System Error Log',
        size: '3.8MB',
        source: 'https://picsum.photos/1280/720?random=12',
      },
    ],
    attachments: [
      {
        filename: 'system_outage_report.pdf',
        size: '1.8MB',
        url: 'https://example.com/attachments/system_outage_report_4.pdf',
      },
    ],
    updates: [
      {
        timestamp: '2024-11-14T08:30:00Z',
        relativeTime: '4 days ago',
        loggedBy: 'System',
        update: 'Critical system failure reported to IT Support.',
        resolved: false,
      },
      {
        timestamp: '2024-11-14T12:45:00Z',
        relativeTime: '4 days ago',
        loggedBy: 'Ethan Hayes',
        update: 'System restored. Beginning recovery procedures.',
        resolved: false,
      },
      {
        timestamp: '2024-11-14T16:20:00Z',
        relativeTime: '4 days ago',
        loggedBy: 'System',
        update: 'Recovery procedures completed successfully.',
        resolved: true,
        proposedResolution: {
          rootCause: 'Equipment Failure',
          rootCauseDetails:
            'Critical failure in primary sorting belt mechanism due to inadequate preventive maintenance.',
          correctiveAction: 'Equipment Maintenance',
          correctiveActionDetails:
            'Manufacturer consultation in progress for complete system overhaul and implementation of predictive maintenance schedule.',
          status: 'pending',
        },
      },
    ],
  },
  {
    id: 5,
    businessName: 'Sustainable Recycling Co',
    delegatedPerson: 'Rachel Green',
    flagged: true,
    description:
      '<p>Regular inspection revealed <b>non-compliance with updated waste segregation regulations</b> in our sorting facility. Several containers were found to be incorrectly labeled and sorted.</p><p>This poses a risk to our certification renewal due next month.</p>',
    raisedBy: 'Emma Hall',
    timestamp: '2024-11-13T15:20:00Z',
    relativeTime: '5 days ago',
    advisedRootCause: 'Documentation Error',
    advisedCorrectiveAction: 'Paperwork Audit',
    departmentResponsible: 'Compliance',
    type: 'Issue',
    open: true,
    unseenUpdates: 2,
    images: [],
    attachments: [
      {
        filename: 'compliance_audit.pdf',
        size: '2.1MB',
        url: 'https://example.com/attachments/compliance_audit_5.pdf',
      },
    ],
    updates: [
      {
        timestamp: '2024-11-13T15:20:00Z',
        relativeTime: '5 days ago',
        loggedBy: 'System',
        update: 'Compliance issue reported.',
        resolved: false,
      },
      {
        timestamp: '2024-11-14T09:30:00Z',
        relativeTime: '4 days ago',
        loggedBy: 'Rachel Green',
        update: 'Initial assessment completed. Documentation review in progress.',
        resolved: false,
      },
      {
        timestamp: '2024-11-14T14:45:00Z',
        relativeTime: '4 days ago',
        loggedBy: 'System',
        update: 'Updated sorting procedures implemented.',
        resolved: false,
      },
      {
        timestamp: '2024-11-15T11:20:00Z',
        relativeTime: '3 days ago',
        loggedBy: 'Michael Scott',
        update: 'Staff training scheduled for compliance procedures.',
        resolved: false,
      },
    ],
  },
  {
    id: 6,
    businessName: 'Harbor Industrial Park',
    delegatedPerson: 'Henry Watson',
    flagged: false,
    description:
      '<p>Multiple employees reported <b>unsafe working conditions</b> in the vehicle maintenance bay. Issues include poor ventilation, inadequate lighting, and worn-out safety equipment.</p><p>This requires immediate attention to prevent potential workplace incidents.</p>',
    raisedBy: 'Liam Adams',
    timestamp: '2024-11-12T09:45:00Z',
    relativeTime: '6 days ago',
    advisedRootCause: 'Hazardous Conditions',
    advisedCorrectiveAction: 'Safety Inspection',
    departmentResponsible: 'Safety',
    type: 'Issue',
    open: false,
    unseenUpdates: 0,
    images: [
      {
        title: 'Maintenance Bay Conditions',
        size: '4.2MB',
        source: 'https://picsum.photos/1280/720?random=13',
      },
    ],
    attachments: [],
    updates: [
      {
        timestamp: '2024-11-12T09:45:00Z',
        relativeTime: '6 days ago',
        loggedBy: 'System',
        update: 'Safety concern reported.',
        resolved: false,
      },
      {
        timestamp: '2024-11-13T16:30:00Z',
        relativeTime: '5 days ago',
        loggedBy: 'Henry Watson',
        update: 'Safety inspection completed. All issues addressed.',
        resolved: true,
        proposedResolution: {
          rootCause: 'Hazardous Conditions',
          correctiveAction: 'Comprehensive Safety Inspection',
          status: 'accepted',
        },
      },
      {
        timestamp: '2024-11-14T10:15:00Z',
        relativeTime: '4 days ago',
        loggedBy: 'System',
        update: 'Follow-up inspection scheduled for next week.',
        resolved: false,
      },
    ],
  },
  {
    id: 7,
    businessName: 'City Central Hospital',
    delegatedPerson: 'Logan Evans',
    flagged: true,
    description:
      '<p>Critical shortage of <b>specialized medical waste containers</b> reported across multiple hospital departments. Current inventory levels are at 15% of required capacity.</p><p>This situation risks disrupting essential medical services if not addressed within 48 hours.</p>',
    raisedBy: 'Sophia Reed',
    timestamp: '2024-11-11T14:15:00Z',
    relativeTime: '7 days ago',
    advisedRootCause: 'Resource Shortage',
    advisedCorrectiveAction: 'Additional Staffing',
    departmentResponsible: 'Logistics',
    type: 'Disaster',
    open: false,
    unseenUpdates: 0,
    images: [
      {
        title: 'Empty Medical Supply Storage',
        size: '3.9MB',
        source: 'https://picsum.photos/1280/720?random=14',
      },
    ],
    attachments: [
      {
        filename: 'emergency_supply_report.pdf',
        size: '1.5MB',
        url: 'https://example.com/attachments/emergency_supply_report_7.pdf',
      },
    ],
    updates: [
      {
        timestamp: '2024-11-11T14:15:00Z',
        relativeTime: '7 days ago',
        loggedBy: 'System',
        update: 'Emergency supply shortage reported.',
        resolved: false,
      },
      {
        timestamp: '2024-11-12T10:00:00Z',
        relativeTime: '6 days ago',
        loggedBy: 'Logan Evans',
        update: 'Emergency supplies delivered. Inventory restored to required levels.',
        resolved: true,
        proposedResolution: {
          rootCause: 'Resource Shortage',
          correctiveAction: 'Deploy Additional Staffing',
          status: 'accepted',
        },
      },
      {
        timestamp: '2024-11-12T15:30:00Z',
        relativeTime: '6 days ago',
        loggedBy: 'System',
        update: 'Inventory management system updated with new minimum stock levels.',
        resolved: false,
      },
      {
        timestamp: '2024-11-13T09:45:00Z',
        relativeTime: '5 days ago',
        loggedBy: 'Emma Parker',
        update: 'New supplier agreements established for emergency situations.',
        resolved: false,
      },
      {
        timestamp: '2024-11-14T11:20:00Z',
        relativeTime: '4 days ago',
        loggedBy: 'System',
        update: 'Case review completed. Preventive measures documented.',
        resolved: false,
      },
    ],
  },
  {
    id: 8,
    businessName: 'GreenLeaf Processing',
    delegatedPerson: 'Jessica Thompson',
    flagged: false,
    description:
      '<p>High turnover rate in the sorting facility team has led to <b>significant processing delays</b>. New staff lack proper training, resulting in increased error rates and slower processing times.</p><p>Current backlog is estimated at 3 days worth of materials.</p>',
    raisedBy: 'Harper Price',
    timestamp: '2024-11-10T11:30:00Z',
    relativeTime: '8 days ago',
    advisedRootCause: 'Inadequate Training',
    advisedCorrectiveAction: 'Enhanced Driver Training',
    departmentResponsible: 'Human Resources',
    type: 'Issue',
    open: true,
    unseenUpdates: 0,
    images: [],
    attachments: [],
    updates: [
      {
        timestamp: '2024-11-10T11:30:00Z',
        relativeTime: '8 days ago',
        loggedBy: 'System',
        update: 'Staffing and training issue reported to HR.',
        resolved: false,
      },
      {
        timestamp: '2024-11-11T14:20:00Z',
        relativeTime: '7 days ago',
        loggedBy: 'Jessica Thompson',
        update: 'Training program review initiated.',
        resolved: false,
      },
    ],
  },
  {
    id: 9,
    businessName: 'Downtown Business District',
    delegatedPerson: 'Mia Bryant',
    flagged: false,
    description:
      '<p>Multiple businesses reported <b>missed collections during peak hours</b>. Investigation reveals poor route optimization causing trucks to arrive during high-traffic periods.</p><p>This has resulted in complaints from 12 major clients in the district.</p>',
    raisedBy: 'Jacob Hamilton',
    timestamp: '2024-11-09T16:45:00Z',
    relativeTime: '9 days ago',
    advisedRootCause: 'Poor Route Planning',
    advisedCorrectiveAction: 'Route and Checklist Review',
    departmentResponsible: 'Operations',
    type: 'Issue',
    open: false,
    unseenUpdates: 0,
    images: [
      {
        title: 'Traffic Congestion',
        size: '4.1MB',
        source: 'https://picsum.photos/1280/720?random=15',
      },
    ],
    attachments: [
      {
        filename: 'route_analysis.pdf',
        size: '1.7MB',
        url: 'https://example.com/attachments/route_analysis_9.pdf',
      },
    ],
    updates: [
      {
        timestamp: '2024-11-09T16:45:00Z',
        relativeTime: '9 days ago',
        loggedBy: 'System',
        update: 'Route optimization issue reported.',
        resolved: false,
      },
      {
        timestamp: '2024-11-11T09:30:00Z',
        relativeTime: '7 days ago',
        loggedBy: 'Mia Bryant',
        update: 'Routes restructured and optimized for business district.',
        resolved: true,
        proposedResolution: {
          rootCause: 'Poor Route Planning',
          rootCauseDetails:
            'Container placement created accessibility issues during peak hours, leading to collection delays.',
          correctiveAction: 'Schedule Optimization',
          correctiveActionDetails:
            'Redesigned container layout and implemented off-peak collection schedule to avoid congestion.',
          status: 'accepted',
        },
      },
      {
        timestamp: '2024-11-11T16:15:00Z',
        relativeTime: '7 days ago',
        loggedBy: 'System',
        update: 'New route schedules implemented successfully.',
        resolved: false,
      },
    ],
  },
  {
    id: 10,
    businessName: 'Riverside Apartments',
    delegatedPerson: 'David Wilson',
    flagged: false,
    description:
      '<p>Compactor unit #247 has <b>completely broken down</b>, affecting waste management for a 500-unit residential complex. Hydraulic system failure identified as the primary cause.</p><p>Temporary bins are insufficient for the volume of waste generated.</p>',
    raisedBy: 'Lucas Peterson',
    timestamp: '2024-11-08T13:20:00Z',
    relativeTime: '10 days ago',
    advisedRootCause: 'Equipment Failure',
    advisedCorrectiveAction: 'Equipment Maintenance',
    departmentResponsible: 'Maintenance',
    type: 'Issue',
    open: true,
    unseenUpdates: 0,
    images: [
      {
        title: 'Broken Compactor',
        size: '3.7MB',
        source: 'https://picsum.photos/1280/720?random=16',
      },
    ],
    attachments: [
      {
        filename: 'maintenance_report.pdf',
        size: '1.9MB',
        url: 'https://example.com/attachments/maintenance_report_10.pdf',
      },
    ],
    updates: [
      {
        timestamp: '2024-11-08T13:20:00Z',
        relativeTime: '10 days ago',
        loggedBy: 'System',
        update: 'Equipment failure reported to Maintenance.',
        resolved: false,
      },
      {
        timestamp: '2024-11-09T08:45:00Z',
        relativeTime: '9 days ago',
        loggedBy: 'David Wilson',
        update: 'Initial assessment completed. Parts ordered for repair.',
        resolved: false,
      },
      {
        timestamp: '2024-11-10T14:30:00Z',
        relativeTime: '8 days ago',
        loggedBy: 'System',
        update: 'Temporary waste management solution implemented.',
        resolved: false,
      },
    ],
  },
  {
    id: 11,
    businessName: 'Express Logistics Hub',
    delegatedPerson: 'Robert Chen',
    flagged: true,
    description:
      '<p>Critical failure in the <b>automated waste sorting system</b> has caused a complete shutdown of the recycling line. Initial assessment indicates a major mechanical failure in the primary sorting belt.</p><p>All incoming recyclables are being redirected to temporary storage.</p>',
    raisedBy: 'Amelia Bennett',
    timestamp: '2024-11-07T10:15:00Z',
    relativeTime: '11 days ago',
    advisedRootCause: 'Equipment Failure',
    advisedCorrectiveAction: 'Equipment Maintenance',
    departmentResponsible: 'Maintenance',
    type: 'Disaster',
    open: true,
    images: [
      {
        title: 'Sorting System Failure',
        size: '4.3MB',
        source: 'https://picsum.photos/1280/720?random=17',
      },
    ],
    attachments: [
      {
        filename: 'system_failure_report.pdf',
        size: '2.5MB',
        url: 'https://example.com/attachments/system_failure_report_11.pdf',
      },
    ],
    updates: [
      {
        timestamp: '2024-11-07T10:15:00Z',
        relativeTime: '11 days ago',
        loggedBy: 'System',
        update: 'Critical system failure reported.',
        resolved: false,
      },
      {
        timestamp: '2024-11-08T09:30:00Z',
        relativeTime: '10 days ago',
        loggedBy: 'Robert Chen',
        update: 'Engineering team deployed for emergency repairs.',
        resolved: false,
      },
      {
        timestamp: '2024-11-09T11:45:00Z',
        relativeTime: '9 days ago',
        loggedBy: 'System',
        update: 'Temporary sorting line established.',
        resolved: false,
      },
      {
        timestamp: '2024-11-10T15:20:00Z',
        relativeTime: '8 days ago',
        loggedBy: 'Sarah Miller',
        update: 'Equipment manufacturer consulted for permanent solution.',
        resolved: false,
        proposedResolution: {
          rootCause: 'Equipment Failure',
          rootCauseDetails:
            'Critical failure in primary sorting belt mechanism due to inadequate preventive maintenance.',
          correctiveAction: 'Equipment Maintenance',
          correctiveActionDetails:
            'Manufacturer consultation in progress for complete system overhaul and implementation of predictive maintenance schedule.',
          status: 'pending',
        },
      },
    ],
    unseenUpdates: 2,
  },
  {
    id: 12,
    businessName: 'North Shore Medical Center',
    delegatedPerson: 'Ava Powell',
    flagged: true,
    description:
      '<p>Dispatch failed to <b>communicate schedule changes</b> to the medical waste collection team, resulting in missed pickups at three critical care units.</p><p>Hospital administration has escalated this as a serious breach of service agreement.</p>',
    raisedBy: 'Ellie Gray',
    timestamp: '2024-11-06T14:40:00Z',
    relativeTime: '12 days ago',
    advisedRootCause: 'Miscommunication',
    advisedCorrectiveAction: 'Communication Protocol Update',
    departmentResponsible: 'Dispatch',
    type: 'Issue',
    open: false,
    images: [
      {
        title: 'Missed Collection Sites',
        size: '3.5MB',
        source: 'https://picsum.photos/1280/720?random=18',
      },
    ],
    attachments: [
      {
        filename: 'incident_report.pdf',
        size: '1.6MB',
        url: 'https://example.com/attachments/incident_report_12.pdf',
      },
    ],
    updates: [
      {
        timestamp: '2024-11-06T14:40:00Z',
        relativeTime: '12 days ago',
        loggedBy: 'System',
        update: 'Communication failure reported to Dispatch.',
        resolved: false,
      },
      {
        timestamp: '2024-11-07T09:15:00Z',
        relativeTime: '11 days ago',
        loggedBy: 'Ava Powell',
        update: 'Emergency collection completed. New communication protocols implemented.',
        resolved: true,
        proposedResolution: {
          rootCause: 'Miscommunication',
          rootCauseDetails:
            'Critical breakdown in communication between dispatch and medical waste collection team due to outdated contact procedures.',
          correctiveAction: 'Update Communication Protocols',
          correctiveActionDetails:
            'Implemented new emergency communication system with redundant notification paths and mandatory acknowledgment for medical facility collections.',
          status: 'accepted',
        },
      },
      {
        timestamp: '2024-11-07T15:30:00Z',
        relativeTime: '11 days ago',
        loggedBy: 'System',
        update: 'Staff briefing conducted on new protocols.',
        resolved: true,
      },
      {
        timestamp: '2024-11-08T10:45:00Z',
        relativeTime: '10 days ago',
        loggedBy: 'Emma Thompson',
        update: 'Follow-up with affected units completed.',
        resolved: true,
      },
      {
        timestamp: '2024-11-09T13:20:00Z',
        relativeTime: '9 days ago',
        loggedBy: 'System',
        update: 'Case review completed. Preventive measures documented.',
        resolved: true,
      },
    ],
    unseenUpdates: 0,
  },
  {
    id: 13,
    businessName: 'Pacific Industrial Park',
    delegatedPerson: 'Lisa Chen',
    flagged: false,
    description:
      '<p>Vehicle maintenance records audit revealed <b>systematic documentation gaps</b> in the fleet management system. Several vehicles are overdue for critical safety inspections.</p><p>This poses significant compliance and safety risks to our operations.</p>',
    raisedBy: 'Jackson Barnes',
    timestamp: '2024-11-05T11:25:00Z',
    relativeTime: '13 days ago',
    advisedRootCause: 'Documentation Error',
    advisedCorrectiveAction: 'Paperwork Audit',
    departmentResponsible: 'Fleet Management',
    type: 'Issue',
    open: true,
    images: [
      {
        title: 'Vehicle Inspection Records',
        size: '4.0MB',
        source: 'https://picsum.photos/1280/720?random=19',
      },
    ],
    attachments: [
      {
        filename: 'audit_findings.pdf',
        size: '2.2MB',
        url: 'https://example.com/attachments/audit_findings_13.pdf',
      },
    ],
    updates: [
      {
        timestamp: '2024-11-05T11:25:00Z',
        relativeTime: '13 days ago',
        loggedBy: 'System',
        update: 'Documentation issue reported to Fleet Management.',
        resolved: false,
      },
      {
        timestamp: '2024-11-06T09:40:00Z',
        relativeTime: '12 days ago',
        loggedBy: 'Michael Brown',
        update: 'Audit team assigned for comprehensive review.',
        resolved: false,
      },
      {
        timestamp: '2024-11-07T14:15:00Z',
        relativeTime: '11 days ago',
        loggedBy: 'System',
        update: 'Initial documentation review completed.',
        resolved: false,
      },
      {
        timestamp: '2024-11-08T11:30:00Z',
        relativeTime: '10 days ago',
        loggedBy: 'Lisa Chen',
        update: 'Vehicle inspection schedule updated.',
        resolved: false,
      },
    ],
    unseenUpdates: 0,
  },
  {
    id: 14,
    businessName: 'Mountain View Tech Campus',
    delegatedPerson: 'Dr. James Wilson',
    flagged: true,
    description:
      '<p>A <b>hazardous chemical spill</b> occurred during waste transfer operations in Building C. Approximately 20 liters of corrosive material was improperly contained.</p><p>Emergency protocols were activated, but decontamination procedures are still pending.</p>',
    raisedBy: 'Oliver Wilson',
    timestamp: '2024-11-04T09:30:00Z',
    relativeTime: '14 days ago',
    advisedRootCause: 'Protocol Violation',
    advisedCorrectiveAction: 'Safety Protocol Review',
    departmentResponsible: 'Safety',
    type: 'Disaster',
    open: true,
    images: [
      {
        title: 'Spill Area',
        size: '4.8MB',
        source: 'https://picsum.photos/1280/720?random=20',
      },
    ],
    attachments: [
      {
        filename: 'incident_report.pdf',
        size: '3.1MB',
        url: 'https://example.com/attachments/incident_report_14.pdf',
      },
    ],
    updates: [
      {
        timestamp: '2024-11-04T09:30:00Z',
        relativeTime: '14 days ago',
        loggedBy: 'System',
        update: 'Chemical spill reported to Safety Department.',
        resolved: false,
      },
      {
        timestamp: '2024-11-04T11:45:00Z',
        relativeTime: '14 days ago',
        loggedBy: 'Dr. James Wilson',
        update: 'Hazmat team deployed to site.',
        resolved: false,
      },
      {
        timestamp: '2024-11-04T15:20:00Z',
        relativeTime: '14 days ago',
        loggedBy: 'System',
        update: 'Initial containment achieved.',
        resolved: false,
      },
    ],
    unseenUpdates: 1,
  },
  {
    id: 15,
    businessName: 'Sunset Mall Complex',
    delegatedPerson: 'Nathan Parker',
    flagged: false,
    description:
      '<p>Recurring issues with <b>waste container accessibility</b> in the food court area. Service staff report difficulty accessing containers during peak hours due to vendor equipment blocking pathways.</p><p>This has led to collection delays and potential health code violations.</p>',
    raisedBy: 'Sophie Martinez',
    timestamp: '2024-11-03T16:20:00Z',
    relativeTime: '15 days ago',
    advisedRootCause: 'Access Obstruction',
    advisedCorrectiveAction: 'Layout Modification',
    departmentResponsible: 'Operations',
    type: 'Issue',
    open: false,
    images: [
      {
        title: 'Blocked Access Path',
        size: '3.9MB',
        source: 'https://picsum.photos/1280/720?random=21',
      },
    ],
    attachments: [],
    updates: [
      {
        timestamp: '2024-11-03T16:20:00Z',
        relativeTime: '15 days ago',
        loggedBy: 'System',
        update: 'Access issue reported to Operations.',
        resolved: false,
      },
      {
        timestamp: '2024-11-04T11:45:00Z',
        relativeTime: '14 days ago',
        loggedBy: 'Nathan Parker',
        update: 'New container placement implemented. Access paths cleared.',
        resolved: true,
        proposedResolution: {
          rootCause: 'Poor Route Planning',
          rootCauseDetails:
            'Container placement created accessibility issues during peak hours, leading to collection delays.',
          correctiveAction: 'Schedule Optimization',
          correctiveActionDetails:
            'Redesigned container layout and implemented off-peak collection schedule to avoid congestion.',
          status: 'accepted',
        },
      },
      {
        timestamp: '2024-11-04T16:30:00Z',
        relativeTime: '14 days ago',
        loggedBy: 'System',
        update: 'Vendor compliance guidelines updated.',
        resolved: false,
      },
      {
        timestamp: '2024-11-05T09:15:00Z',
        relativeTime: '13 days ago',
        loggedBy: 'Sophie Martinez',
        update: 'Staff training completed on new layout.',
        resolved: false,
      },
    ],
    unseenUpdates: 0,
  },
  {
    id: 16,
    businessName: 'Harbor View Hotel',
    delegatedPerson: 'Robert Turner',
    flagged: true,
    description:
      '<p>Multiple guests reported <b>strong odors</b> from the waste storage area near the pool deck. Investigation revealed malfunctioning ventilation system and improper sealing of organic waste containers.</p><p>This is affecting guest satisfaction and online reviews.</p>',
    raisedBy: 'William Chen',
    timestamp: '2024-11-02T13:15:00Z',
    relativeTime: '16 days ago',
    advisedRootCause: 'Equipment Failure',
    advisedCorrectiveAction: 'Equipment Maintenance',
    departmentResponsible: 'Maintenance',
    type: 'Issue',
    open: true,
    images: [
      {
        title: 'Ventilation System',
        size: '4.2MB',
        source: 'https://picsum.photos/1280/720?random=22',
      },
    ],
    attachments: [
      {
        filename: 'guest_complaints.pdf',
        size: '1.8MB',
        url: 'https://example.com/attachments/guest_complaints_16.pdf',
      },
    ],
    updates: [
      {
        timestamp: '2024-11-02T13:15:00Z',
        relativeTime: '16 days ago',
        loggedBy: 'System',
        update: 'Odor complaint reported to Maintenance.',
        resolved: false,
      },
      {
        timestamp: '2024-11-03T09:30:00Z',
        relativeTime: '15 days ago',
        loggedBy: 'Robert Turner',
        update: 'Ventilation system inspection completed.',
        resolved: false,
      },
      {
        timestamp: '2024-11-03T15:45:00Z',
        relativeTime: '15 days ago',
        loggedBy: 'System',
        update: 'Repair parts ordered for ventilation system.',
        resolved: false,
      },
      {
        timestamp: '2024-11-04T10:20:00Z',
        relativeTime: '14 days ago',
        loggedBy: 'William Chen',
        update: 'Temporary odor control measures implemented.',
        resolved: false,
      },
      {
        timestamp: '2024-11-05T13:40:00Z',
        relativeTime: '13 days ago',
        loggedBy: 'System',
        update: 'Guest compensation process initiated.',
        resolved: false,
      },
    ],
    unseenUpdates: 0,
  },
  {
    id: 17,
    businessName: 'Eastside Manufacturing',
    delegatedPerson: null,
    flagged: true,
    description:
      '<p>Critical failure in the <b>industrial waste processing unit</b> has halted production line operations. Initial assessment indicates electrical system malfunction affecting the compactor mechanisms.</p><p>Emergency maintenance required to prevent production backlog.</p>',
    raisedBy: 'Benjamin Foster',
    timestamp: '2024-11-01T10:45:00Z',
    relativeTime: '17 days ago',
    advisedRootCause: 'Equipment Failure',
    advisedCorrectiveAction: 'Equipment Maintenance',
    departmentResponsible: 'Maintenance',
    type: 'Disaster',
    open: false,
    images: [
      {
        title: 'Failed Processing Unit',
        size: '5.1MB',
        source: 'https://picsum.photos/1280/720?random=23',
      },
    ],
    attachments: [
      {
        filename: 'maintenance_report.pdf',
        size: '2.7MB',
        url: 'https://example.com/attachments/maintenance_report_17.pdf',
      },
    ],
    updates: [
      {
        timestamp: '2024-11-01T10:45:00Z',
        relativeTime: '17 days ago',
        loggedBy: 'System',
        update: 'Equipment failure reported to Maintenance.',
        resolved: false,
      },
      {
        timestamp: '2024-11-02T08:30:00Z',
        relativeTime: '16 days ago',
        loggedBy: 'Michael Torres',
        update: 'Emergency repairs completed. Unit back online.',
        resolved: true,
        proposedResolution: {
          rootCause: 'Equipment Failure',
          rootCauseDetails:
            'Electrical system malfunction in compactor unit caused by power surge and outdated circuit protection.',
          correctiveAction: 'Equipment Maintenance',
          correctiveActionDetails:
            'Installed new circuit protection systems and implemented emergency backup power supply for critical equipment.',
          status: 'accepted',
        },
      },
      {
        timestamp: '2024-11-02T13:15:00Z',
        relativeTime: '16 days ago',
        loggedBy: 'System',
        update: 'Production resumed at full capacity.',
        resolved: false,
      },
    ],
    unseenUpdates: 0,
  },
  {
    id: 18,
    businessName: 'Central City Schools',
    delegatedPerson: 'Emily Watson',
    flagged: false,
    description:
      '<p>School district reports <b>inconsistent waste collection schedules</b> across multiple locations. Several schools experiencing overflow situations due to missed pickups.</p><p>Coordination with school hours and safety protocols needs immediate attention.</p>',
    raisedBy: 'Emily Watson',
    timestamp: '2024-10-31T14:20:00Z',
    relativeTime: '18 days ago',
    advisedRootCause: 'Schedule Mismanagement',
    advisedCorrectiveAction: 'Route and Checklist Review',
    departmentResponsible: 'Operations',
    type: 'Issue',
    open: true,
    images: [
      {
        title: 'Overflowing Bins',
        size: '3.8MB',
        source: 'https://picsum.photos/1280/720?random=24',
      },
    ],
    attachments: [
      {
        filename: 'schedule_analysis.xlsx',
        size: '1.5MB',
        url: 'https://example.com/attachments/schedule_analysis_18.xlsx',
      },
    ],
    updates: [
      {
        timestamp: '2024-10-31T14:20:00Z',
        relativeTime: '18 days ago',
        loggedBy: 'System',
        update: 'Schedule issues reported to Operations.',
        resolved: false,
      },
      {
        timestamp: '2024-11-01T09:45:00Z',
        relativeTime: '17 days ago',
        loggedBy: 'Emily Watson',
        update: 'Route analysis initiated for all school locations.',
        resolved: false,
      },
    ],
    unseenUpdates: 0,
  },
  {
    id: 19,
    businessName: 'Riverfront Restaurants',
    delegatedPerson: 'Alexandra Kim',
    flagged: true,
    description:
      '<p>Health inspector identified <b>cross-contamination risks</b> in the shared waste disposal area serving multiple restaurants. Improper separation of food waste and recyclables noted.</p><p>Immediate corrective action required to maintain health department compliance.</p>',
    raisedBy: 'Alexandra Kim',
    timestamp: '2024-10-30T11:35:00Z',
    relativeTime: '19 days ago',
    advisedRootCause: 'Protocol Violation',
    advisedCorrectiveAction: 'Safety Protocol Review',
    departmentResponsible: 'Compliance',
    type: 'Issue',
    open: true,
    images: [
      {
        title: 'Waste Area Conditions',
        size: '4.5MB',
        source: 'https://picsum.photos/1280/720?random=25',
      },
    ],
    attachments: [
      {
        filename: 'inspection_report.pdf',
        size: '2.3MB',
        url: 'https://example.com/attachments/inspection_report_19.pdf',
      },
    ],
    updates: [
      {
        timestamp: '2024-10-30T11:35:00Z',
        relativeTime: '19 days ago',
        loggedBy: 'System',
        update: 'Health code violation reported to Compliance.',
        resolved: false,
      },
    ],
    unseenUpdates: 0,
  },
]
